name: Digitraffic
gems:
  - jekyll-babel
sass:
  sass_dir: _scss
compress_html:
  clippings: all
exclude: [README.md,node_modules, gulpfile.js, Gemfile, package.json, package-lock.json, metadata, docs]
collections:
  applications:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: "img"
    values:
      image: true
  -
    scope:
      path: ""
      type: "applications"
    values:
      layout: "application"