name: Digitraffic
sass:
  sass_dir: _scss
exclude: [node_modules, gulpfile.js]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: "img"
    values:
      image: true