name: Digitraffic
baseurl: /digitraffic
gems:
  - jekyll-babel
sass:
  sass_dir: _scss
  style: compressed
compress_html:
  clippings: all
  comments: all
exclude: [README.md,node_modules, gulpfile.js, Gemfile, package.json, package-lock.json, metadata, docs]
collections:
  applications:
    output: true
    permalink: /sovellukset/:name.html
  developments:
    output: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
      categories: "Tiedotteet"
      traffictypes: "Tieliikenne"
  -
    scope:
      path: "img"
    values:
      image: true
  -
    scope:
      path: ""
      type: "applications"
    values:
      layout: "application"
      hero-image: "road"
      logo: "application-default-logo.svg"