name: Digitraffic
gems:
  - jekyll-babel
sass:
  sass_dir: _scss
exclude: [README.md,node_modules, gulpfile.js, Gemfile, package.json, package-lock.json, metadata, docs]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: "img"
    values:
      image: true